- defaults:
    link:
      create: true
      relink: true
      glob: true
    shell:
      quiet: true
      stdout: false
      stderr: true

- clean:
    - '~'
    - '~/.config/dunst/'
    - '~/.config/systemd/user/'
    - '~/.config/rofi/'
    - '~/.config/tilix/'
    - '~/.sbt/1.0/plugins/'

- link:
    ~/.config/dunst: config/dunst
    ~/.config/rofi: config/rofi
    ~/.config/systemd/user:
      path: config/systemd/user/*
    ~/.config/tilix:
      path: config/tilix/*
    ~/.gitconfig:
    ~/.gitignore:
    ~/.i3:
    ~/.local/share/applications:
      path: applications/*
    ~/.sbt/1.0/plugins:
      path: sbt/plugins/*
    ~/.tmux.conf:
    ~/.Xkbmap:
    ~/.zshrc:

- shell:
    - description: "[TMUX] Installing Tmux Plugin Manager (TPM)"
      command: >
        [ -d ~/.tmux/plugins/tpm ] ||
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

    -
      description: "[ZSH] Installing zplug"
      command: >
        [ -d ~/.zplug ] ||
        git clone https://github.com/zplug/zplug ~/.zplug
