- defaults:
    shell:
      quiet: true
      stdout: false
      stderr: true

- shell:
    - description: "[TMUX] Installing Tmux Plugin Manager (TPM)"
      command: >
        [ -d ~/.tmux/plugins/tpm ] ||
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
