- defaults:
    link:
      create: true
      relink: true
      glob: true

- clean:
    - '~'
    - '~/.config/systemd/user/'
    - '~/.config/rofi/'
    - '~/.config/tilix/'
    - '~/.sbt/1.0/plugins/'

- link:
    ~/.config/rofi: config/rofi
    ~/.config/systemd/user:
      path: config/systemd/user/*
    ~/.config/tilix:
      path: config/tilix/*
    ~/.dunstrc: dunstrc
    ~/.gitconfig: gitconfig
    ~/.gitignore: gitignore
    ~/.i3: i3
    ~/.local/share/applications:
      path: applications/*
    ~/.sbt/1.0/plugins:
      path: sbt/plugins/*
    ~/.tmux.conf: tmux.conf
    ~/.Xmodmap: Xmodmap
    ~/.Xresources: Xresources
    ~/.xsession: xsession
    ~/.zshrc: zshrc

- shell:

    - description: "[PACMAN] Adding mirror updating using reflector"
      command: >
        sudo mkdir -p /etc/pacman.d/hooks &&
        sudo ln -sf /home/jmartinez/.dotfiles/pacman.d/hooks/mirrorupgrade.hook /etc/pacman.d/hooks/mirrorupgrade.hook

    - description: "[TMUX] Installing Tmux Plugin Manager (TPM)"
      command: >
        [ -d ~/.tmux/plugins/tpm ] ||
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

    -
      description: "[ZSH] Installing Oh-My-Zsh"
      command:  >
        [ -d ~/.oh-my-zsh ] ||
        git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

    -
      description: "[ZSH] Installing powerlevel9k theme"
      command: >
        [ -d ~/.dotfiles/zsh/themes/powerlevel9k ] ||
        git clone https://github.com/bhilburn/powerlevel9k.git ~/.dotfiles/zsh/themes/powerlevel9k

    -
      description: "[ZSH] Installing zsh-syntax-highlighting"
      command: >
        [ -d ~/.dotfiles/zsh/plugins/zsh-syntax-highlighting ] ||
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.dotfiles/zsh/plugins/zsh-autosuggestions

    -
      description: "[ZSH] Installing zsh-autosuggestions"
      command: >
        [ -d ~/.dotfiles/zsh/plugins/zsh-autosuggestions ] ||
        git clone https://github.com/zsh-users/zsh-autosuggestions ~/.dotfiles/zsh/plugins/zsh-autosuggestions
